# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 13:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Date_of_birth', models.DateField()),
                ('Email', models.EmailField(blank=True, max_length=30)),
                ('Jabber', models.EmailField(blank=True, max_length=30)),
                ('Skype', models.CharField(max_length=30)),
                ('Other_contacts', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)])),
                ('Bio', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)])),
            ],
        ),
    ]
